In [1]:
import numpy as np

In [6]:
result = 0 
for i in range(100):    
    result += i 

In [7]:
result

4950

In [8]:
[range(i, i + 3) for i in [2, 4, 6]]

[range(2, 5), range(4, 7), range(6, 9)]

In [9]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [10]:
 # Create a length-10 integer array filled with zeros        
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
 # Create a 3x5 floating-point array filled with 1s        
np.ones((3, 5), dtype=float)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
 # Create a 3x5 array filled with 3.14        
np.full((3, 5), 3.14)


array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [15]:
# Create an array filled with a linear sequence 
# Starting at 0, ending at 20, stepping by 2        
# (this is similar to the built-in range() function) 
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
# Create an array of five values evenly spaced between 0 and 1  
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.83578269, 0.06149849, 0.91190408],
       [0.71673674, 0.70198217, 0.0106141 ],
       [0.31136128, 0.62445291, 0.87562663]])

In [18]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.71340235,  0.49112077, -0.35061107],
       [ 0.67695569,  2.01714238, -0.07915043],
       [-0.69511617, -0.94494564, -1.44372204]])

In [19]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))


array([[3, 1, 7],
       [1, 0, 1],
       [9, 2, 4]])

In [21]:
# Create a 3x3 identity matrix        
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)


array([1., 1., 1.])

In [2]:
#Numpy standard data type
np.zeros(10, dtype='int16') 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [3]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [28]:
np.random.seed(0)  # seed for reproducibility
x1 = np.random.randint(10, size=6)  # One-dimensional array       
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array       
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array 

In [29]:
print("x3 ndim: ", x3.ndim)       
print("x3 shape:", x3.shape)       
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [30]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [27]:
 print("dtype:", x3.dtype)

dtype: int32


In [32]:
print("itemsize:", x3.itemsize, "bytes")       
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


In [33]:
x1[0]

5

In [35]:
x1[4]

7

In [36]:
x2[:]

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [39]:
x2[0,1]

5

In [43]:
x2[2,3]=9

In [44]:
x2[2,3]

9

In [45]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 9]])

In [46]:
x1[0]=2.5

In [48]:
x1[0] = 0.002

In [49]:
x1

array([0, 0, 3, 3, 7, 9])